# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly

services:
  - mysql

env:
  global:
    - WP_DEVELOP_DIR=/tmp/wordpress/
  matrix:
    # Trunk
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1

    # Latest stable version
    - WP_VERSION=stable WP_MULTISITE=0
    - WP_VERSION=stable WP_MULTISITE=1
    
    
script:
  - npm run production --verbose
  - php-cs-fixer fix --diff --dry-run
  - psalm --show-info=true
  - phpunit --coverage-text
