blank_issues_enabled: false
contact_links:
  - name: Emergency System
    url: https://github.com/DmitrysXYZ/Emergency-System
    about: Helping people stay alert in the event of a biological hazard.
